# Project information
site_name: MazeDocs
site_description: 'Maze documentation'
site_author: 'Timothe'
site_url: ''

# Copyright
copyright: '&copy; 2021 Timothe'

# Repository
repo_name: 'MazeDocs'
repo_url: ''
edit_uri: ''

use_directory_urls: false

docs_dir: 'notedocs'

theme: 
    name : material
    palette:
        scheme: slate
        primary: deep orange
        accent: teal
    features:
        - navigation.tabs
    highlightjs : true
    hljs_languages :
        - python
        - c++
        - c
        - html
        - css
        - cmd

plugins:
    - search      
   
markdown_extensions:
    - pymdownx.keys
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - attr_list
    - def_list
 
nav:
    - Home: index.md
 
    - Private: 
        - 'Career': 'Private\Career.md'
        - 'Personnal Notes': 'Private\Private.md'
        - 'Stuff to buy': 'Private\Commandes_todo.md'
        
    - Documentation:
        - 'Software' :
            - 'Ongoing tools': 'Documentation\Software\PyTools_ideas.md'
            - 'Position Tracking': 'Documentation\Software\BehaviorToolkit.md'
            
        - 'Hardware' :
            - 'MAZE': 'Documentation\Hardware\Maze.md'
            - 'MORJ' : 'Documentation\Hardware\MORJ.md'
            - 'Snapmaker 2' : 'Documentation\ExternalHardware\Snapmaker2.md'
            - 'Ultimaker S5' : 'Documentation\ExternalHardware\UlimakerS5.md'
            - 'Proxxon 500BL' : 'Documentation\ExternalHardware\Proxxon500BL.md'
            
    - Analysis notes: 
        - 'Expect 2': 'Analysis\Expect_2.md'
        - 'Expect 3': 'Analysis\Expect_3.md'
        - 'Expect Controls': 'Analysis\Expect_controls.md'
        - 'MORJ_paper': 'Analysis\MORJ_quantif.md'
        
    - Lab :
        - 'Cahier de manip': 'Lab\ELNTim.md'
        - 'Coffre fort': 'Lab\Lab_codex.md'
        - 'Notes non-datées': 'Lab\Unordered_lab_notes.md'
        - 'Precis pharmaco.': 'Lab\Surgery_pharmacology.md'
        - 'Protocoles':
            - 'Awake VSD staning': 'Lab\Awake_VSD_staining.md'
            - 'Glass window': 'Lab\Glass_window.md'
            - 'Pdms window': 'Lab\PDMS_window.md'
            - 'Glass window opening': 'Lab\Glass_window_opening.md'
            - 'Implantation': 'Lab\Implantation.md'
            - 'Intrinsic imaging': 'Lab\Intrinsic_Imaging.md'
    
    - Bibliography: 
        - 'Neurosciences': 'Biblio\Biblio_codex_2.md'      

        